# Generated by Django 4.2.1 on 2023-05-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('snies', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
                ('modalidad', models.CharField(max_length=18)),
                ('descripcion', models.CharField(max_length=120)),
                ('tituloOtorgado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('numDocumento', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('numDocumento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idFacultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idPrograma', models.AutoField(primary_key=True, serialize=False)),
                ('descripción', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('idSemestre', models.AutoField(primary_key=True, serialize=False)),
                ('descripción', models.CharField(max_length=30)),
                ('totalCreditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idMatricula', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatricula', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.semestre'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.facultad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.programa'),
        ),
    ]
